version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  create_topic:
    build: .
    container_name: create_topic
    depends_on:
      - kafka
    entrypoint: ["python", "-u", "create_topic.py"]
    networks:
      - kafka-net

  producer:
    build: .
    container_name: producer
    depends_on:
      - kafka
    entrypoint: ["python", "-u", "stock_Producer.py"]
    networks:
      - kafka-net

  consumer:
    build: .
    container_name: consumer
    depends_on:
      - kafka
    entrypoint: ["python", "-u", "stock_Consumer.py"]
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
