services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  create_topic:
    build: .
    container_name: create_topic
    depends_on:
      - kafka
    entrypoint: ["python", "-u", "create_topic.py"]
    networks:
      - kafka-net

  producer:
    build: .
    container_name: producer
    environment:
      - wait=60
    depends_on:
      - kafka
      - create_topic
    entrypoint: ["python", "-u", "stock_Producer.py"]
    networks:
      - kafka-net

  consumer:
    build: .
    container_name: consumer
    depends_on:
      - kafka
      - producer
    entrypoint: ["python", "-u", "stock_Consumer.py"]
    networks:
      - kafka-net

  flink-jobmanager:
    image: flink:latest
    container_name: flink-jobmanager
    depends_on:
      - kafka
      - producer
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: jobmanager
    networks:
      - kafka-net

  flink-taskmanager:
    image: flink:latest
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager
    networks:
      - kafka-net
    
  flink-job:
    image: flink:latest
    container_name: flink-job
    depends_on:
      - flink-jobmanager
      - flink-taskmanager
    networks:
      - kafka-net
    entrypoint: ["/bin/bash", "-c", "./bin/flink run -py /opt/flink-jobs/detect_gaps.py"]
    volumes:
      - ./flink_jobs:/opt/flink-jobs

  dashboard:
    build: .
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - consumer
    entrypoint: ["sh", "-c", "sleep 10 && streamlit run visualisation.py --server.port=8501"]
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
